version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2123
      POSTGRES_DB: layer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build:
      context: ./layer-Back
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:2123@db:5432/layer
    depends_on:
      - db
    ports:
      - "8000:8000"

  front:
    build:
      context: ./layer-Front
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - back
    ports:
      - "3000:3000"

volumes:
  postgres_data:
