version: '3.8'

services:
  backend:
    build:
      context: ./layer-Back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - weaviate
    env_file:
      - ./layer-Back/.env
    volumes:
      - ./layer-Back:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./layer-Front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    env_file:
      - ./layer-Front/.env
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2123
      POSTGRES_DB: layer
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: text2vec-openai,grpc
      GRPC_PORT: 50051
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  postgres_data:
  weaviate_data:
