version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2123
      POSTGRES_DB: layer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d layer"]
      interval: 5s
      timeout: 3s
      retries: 10

  back:
    build:
      context: ./layer-back
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./layer-back/.env
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./layer-front
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # 👈 это обязательно!
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      NUXT_PUBLIC_API_BASE: "http://back:8000"

volumes:
  postgres_data:
  # ollama:
