"""Add weaviate_id to documents

Revision ID: 176a82762e1f
Revises: 56823bcc7696
Create Date: 2025-07-25 14:19:14.099568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176a82762e1f'
down_revision: Union[str, None] = '56823bcc7696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('weaviate_id', sa.String(), nullable=True))
    op.drop_index('ix_documents_id', table_name='documents')
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_documents_id', 'documents', ['id'], unique=False)
    op.drop_column('documents', 'weaviate_id')
    # ### end Alembic commands ###
