"""add autoincrement to DocumentModel

Revision ID: 56823bcc7696
Revises: f5eb639ad21c
Create Date: 2025-07-25 12:12:22.371234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56823bcc7696'
down_revision: Union[str, None] = 'f5eb639ad21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
