"""add user_id to casemodel

Revision ID: f5eb639ad21c
Revises: c2780ae58764
Create Date: 2025-07-24 14:03:20.794586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eb639ad21c'
down_revision: Union[str, None] = 'c2780ae58764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cases', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'user_id')
    # ### end Alembic commands ###
